### ISSUE TITLE
Kuna light  issue continues to shut down my Hoobs

### ISSUE THREAD

**Issue by fdiovine** [rasod/homebridge-kunalight#4]
8/16/2020, 11:58:07 PM TypeError: Cannot read property 'statusCode' of undefined
    at KunaAccessory.<anonymous> (/home/hoobs/.hoobs/node_modules/homebridge-kunalight/index.js:107:71)
    at self.callback (/home/hoobs/.hoobs/node_modules/request/request.js:185:22)
    at Request.emit (events.js:310:20)
    at Request.onRequestError (/home/hoobs/.hoobs/node_modules/request/request.js:877:8)
    at ClientRequest.emit (events.js:310:20)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:310:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
8/16/2020, 11:58:07 PM Got SIGTERM, shutting down Bridge...

**Comment by OxfordRancher** [comment]
Similar issue here Kuna results in signal termination (sigterm)

The main issue (may not be related) is my token is expired but I can log in via the Kuna app no issues. Perhaps they (Kuna)?changed the api?

**Comment by OxfordRancher** [comment]
I appear to have the same issue.

Sometimes it's stable for a few days more often it fails within hours sometimes within minutes. ....


statusCode' of undefined
    at KunaAccessory.<anonymous> (/home/hoobs/.hoobs/node_modules/homebridge-kunalight/index.js:107:71)
    at self.callback (/home/hoobs/.hoobs/node_modules/request/request.js:185:22)
    at Request.emit (events.js:310:20)
    at Request.onRequestError (/home/hoobs/.hoobs/node_modules/request/request.js:877:8)
    at ClientRequest.emit (events.js:310:20)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:310:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
11/8/2020, 8:55:22 PM Got SIGTERM, shutting down Bridge...

**Comment by OxfordRancher** [comment]
Issue keeps repeating . Updated hoobs, no change. Tried refreshing kuna app more frequently, no change. Removed stream config from ffmpeg ... result TBD

**Comment by OxfordRancher** [comment]
Really would like this to work. Removed camera but the state error still occurs and crashes hoobs.

Any plans to update the plugin? Would like the camera feed but , I have 2 other cameras so I would settle for light control only.

Minimum needs to be stable at least a few days, longer better and turn off and in the light.

Once its stable I would like my ring motion to turn on light(s).

Authentication Token - Please Check Login Credentials
11/18/2020, 3:49:39 PM TypeError: Cannot read property 'statusCode' of undefined
    at KunaAccessory.<anonymous> (/home/hoobs/.hoobs/node_modules/homebridge-kunalight/index.js:81:55)
    at self.callback (/home/hoobs/.hoobs/node_modules/request/request.js:185:22)
    at Request.emit (events.js:310:20)
    at Request.onRequestError (/home/hoobs/.hoobs/node_modules/request/request.js:877:8)
    at ClientRequest.emit (events.js:310:20)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:310:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
11/18/2020, 3:49:39 PM Got SIGTERM, shutting down Bridge...

**Comment by OxfordRancher** [comment]
Anyone here? Got my ring and Arlo cams somewhat stable on Hoobs, just wanted to see if any changes / updates have been made here? Or what I could do to troubleshoot/ give it a shot looking into sigterm issue ?
